api1: ./traefik --configFile=traefik.toml
api2: uvicorn --port=${PORT:-7000} microservice1proj2:app --reload
api3: uvicorn --port=${PORT:-7001} microservice2proj2:app --reload
api4: uvicorn --port=${PORT:-8000} microserviceproj3:app --reload
api5: uvicorn --port=${PORT:-8001} gameStateService:app --reload
api5: uvicorn --port=${PORT:-8002} Service_Project5:app --reload


